############## Notification door ####################
- alias: 'Telegram bot send message if voordeur is open'
  hide_entity: true
  trigger:
      platform: numeric_state
      entity_id: sensor.fibaro__door_sensor__hal_begane_grond_access_control
      below: 23
  condition:
      condition: and
      conditions:
         - condition: time
           after: '23:00:00'
           before: '08:00:00'
  action:
      service: notify.telegram
      data:
        message: 'Voordeur is open! met data: {{ states.sensor.fibaro__door_sensor__hal_begane_grond_access_control.state }}'
        
#- alias: 'Telegram bot send message if voordeur is open - Vakantie Mode'
#  hide_entity: true
#  trigger:
#      platform: numeric_state
#      entity_id: sensor.fibaro__door_sensor__hal_begane_grond_access_control
#      below: 23
#  action:
#      service: notify.telegram
#      data:
#        message: 'Voordeur is open in de vakantie! met data: {{ states.sensor.fibaro__door_sensor__hal_begane_grond_access_control.state }}'