---
image: docker:latest

stages:
  - preflight
  - dev
  - latest

# Generic preflight template
.preflight: &preflight
  stage: preflight

# Generic test template
.dev: &dev
  stage: dev
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - python -m homeassistant --version
  script:
    - |
      python -m homeassistant \
        --script check_config \
        --info all

.latest: &latest
   stage: latest
   variables:
     PYTHONPATH: "/usr/src/app:$PYTHONPATH"
   before_script:
     - python -m homeassistant --version
     - cp travis_secrets.yaml secrets.yaml
     - touch ./home-assistant_v2.db
     - touch ./home-assistant.log
     - touch ./OZW_Log.txt
   script:
     - hass --script check_config --info all .

# Preflight jobs
shellcheck:
  <<: *preflight
  image:
    name: koalaman/shellcheck-alpine:stable
    entrypoint: [""]
  before_script:
    - shellcheck --version
    - apk --no-cache add grep
    - |
      find . -type f -print0 | \
        xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
  script:
    - |
      for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${ADDON_TARGET}"); do
        if ! shellcheck $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

jsonlint:
  <<: *preflight
  image: sahsu/docker-jsonlint
  before_script:
    - jsonlint --version || true
  script:
    - |
      for file in $(find . -type f -name "*.json"); do
        if ! jsonlint -q $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

markdownlint:
  <<: *preflight
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - gem install mdl
    - mdl --version
  script:
    - mdl --style all --warnings .

# Test jobs
latest:
  <<: *latest
  image:
    name: homeassistant/amd64-homeassistant:latest
    entrypoint: [""]

dev:
  <<: *dev
  image:
    name: homeassistant/home-assistant:dev
    entrypoint: [""]
  allow_failure: true
