language: python
python:
  - "3.6.4"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch /home/travis/build/klaasnicolaas/Smarthome-homeassistant-config/home-assistant_v2.db
  - touch /home/travis/build/klaasnicolaas/Smarthome-homeassistant-config/home-assistant.log
  - touch /home/travis/build/klaasnicolaas/Smarthome-homeassistant-config/OZW_Log.txt
  - touch /home/travis/build/klaasnicolaas/Smarthome-homeassistant-config/ssl/test.pem
  - touch /home/travis/build/klaasnicolaas/Smarthome-homeassistant-config/ssl/testserver.pem
install:
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
notifications:
    email:
      - klaas_schoute@hotmail.com
    on_success: never # default change 
    on_failure: always # default always