- alias: Persoon 1 thuis
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - device_tracker.samsunggalaxys7edgelan
        - device_tracker.samsung_galaxy_s7_edge
        - device_tracker.ce10160afb463b3504
      to: 'home'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: input_boolean.person1_home
      state: 'off'
    - condition: or
      conditions:
      # WiFi and BT are our truth data, as soon as one of them shows us as home we're home
      - condition: state
        entity_id: device_tracker.samsunggalaxys7edgelan
        state: 'home'
      - condition: state
        entity_id: device_tracker.samsung_galaxy_s7_edge
        state: 'home'
      - condition: numeric_state
        entity_id: group.person_person1
        above: 1
        value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person1', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.person1_home