# Slimme meter
- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 5

# Buienradar
- platform: buienradar
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - windspeed
    - groundtemperature
    - precipitation
    
# PostNL
- platform: postnl
  username: !secret username_postnl
  password: !secret password_postnl