---
# Group train
trein_reizen:
  name: Treintijden Trajecten
  entities:
    - sensor.alkmaar_leiden
    - sensor.leiden_alkmaar
    - sensor.schiphol_airport_leiden
    - sensor.leiden_schiphol_airport
    - sensor.alkmaar_amsterdam_sloterdijk
    - sensor.amsterdam_sloterdijk_alkmaar
