---
# Enables a custom component called "versions".
# It is a sensor that fetches the version number of current Home Assistant releases.
#
# https://github.com/custom-components/sensor.versions
#
# THE NEW WAY
# Fetch beta version of HA
- platform: version
  name: Hassbian Beta versie
  beta: true
  image: raspberrypi3-64
  source: pypi

# Fetch stable version of HA
- platform: version
  name: Hassbian Stable versie
  beta: false
  image: raspberrypi3-64
  source: pypi
