################################################
## Packages System
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Binary Sensor
    ################################################

    binary_sensor.db_large:
      <<: *customize
      friendly_name: Database groot

    ################################################
    ## Sensor
    ################################################

    sensor.processor_use:
      <<: *customize
      friendly_name: Processorgebruik

    sensor.memory_use_percent:
      <<: *customize
      friendly_name: Geheugengebruik

    sensor.disk_free_:
      <<: *customize
      friendly_name: Beschikbare opslag

    sensor.disk_use_percent_:
      <<: *customize
      friendly_name: Gebruikte opslag

    sensor.homeassistant_v2db:
      <<: *customize
      friendly_name: Home Assistant Database

    sensor.homeassistantlog:
      <<: *customize
      friendly_name: Home Assistant Logbestand

    sensor.ozw_logtxt:
      <<: *customize
      friendly_name: Home Assistant OZW Logbestand
      
    sensor.configurationyaml:
      <<: *customize
      friendly_name: Home Assistant Configuration

    sensor.cpu_temperature:
      <<: *customize
      friendly_name: Processortemperatuur

    sensor.bad_login:
      <<: *customize
      friendly_name:  Mislukte inlogpogingen
      icon: mdi:alert

    sensor.network_out_eth0:
      <<: *customize
      friendly_name: Bytes verzonden
      icon: mdi:upload-network

    sensor.network_in_eth0:
      <<: *customize
      friendly_name: Bytes ontvangen
      icon: mdi:download-network

    sensor.packets_out_eth0:
      <<: *customize
      friendly_name: Pakketten verzonden
      icon: mdi:upload-network

    sensor.packets_in_eth0:
      <<: *customize
      friendly_name: Pakketten ontvangen
      icon: mdi:download-network

    sensor.myipopendnscom:
      <<: *customize
      friendly_name: Publiek IP-adres
      icon: mdi:network

    sensor.ha_uptime:
      <<: *customize
      friendly_name: Sinds laatste start HA
      icon: mdi:clock
      
    sensor.ha_installed_version:
      <<: *customize
      friendly_name: Hassbian geinstalleerde versie
    
    sensor.python_version:
      <<: *customize
      friendly_name: Python geinstalleerde versie
  ################################################
    ## Group
    ################################################

    group.host_view:
      <<: *customize
      friendly_name: Systeeminformatie
      icon: mdi:server
      order: 80
    
    group.host_performance:
      <<: *customize
      friendly_name: Prestaties
      icon: mdi:memory

    group.host_storage:
      <<: *customize
      friendly_name: Opslag
      icon: mdi:harddisk

    group.host_network:
      <<: *customize
      friendly_name: Netwerk
      icon: mdi:network

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      cpu_high:
        value_template: '{{ states.sensor.processor_use.state | float > 80 }}'
        friendly_name: 'CPU hoog'
  - platform: template
    sensors:
      cpu_hot:
        value_template: '{{ states.sensor.cpu_temperature.state | float > 60 }}'
        friendly_name: 'CPU heet'
  - platform: template
    sensors:
      db_large:
        value_template: '{{ states.sensor.homeassistant_v2db.state | float > 100 }}'

################################################
## Sensor
################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: last_boot
      - type: network_in
        arg: 'eth0'
      - type: network_out
        arg: 'eth0'
      - type: packets_in
        arg: 'eth0'
      - type: packets_out
        arg: 'eth0'
  - platform: command_line
    name: CPU Temperature
    command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: filesize
    file_paths:
      - !secret filesize_homeassistant_db
      - !secret filesize_homeassistant_log
      - !secret filesize_ozw_log
      - !secret filesize_configuration
  - platform: dnsip
  - platform: command_line
    # https://home-assistant.io/components/sensor.command_line/
    name: "HA Uptime"
    command: echo "$(($(date +%s) - $(date -d "$(head -n1 /config/home-assistant.log | cut -d' ' -f-2)" +%s)))"
    scan_interval: 720 # seconds
    value_template: >-
      {% set uptime = value | int %}
      {% set seconds = uptime % 60 %}
      {% set minutes = ((uptime % 3600) / 60) | int %}
      {% set hours = ((uptime % 86400) / 3600) | int %}
      {% set days = (uptime / 86400) | int %}
      {% if days > 0 %}
        {% if days == 1 %}
          1 day
        {% else %}
          {{ days }} days
        {% endif %}
        {{ ', ' }}
      {% endif %}
      {{ '%02d' % hours }}:{{ '%02d' % minutes }}
  - platform: cert_expiry
    host: !secret cert_expiry_host
  - platform: version
    name: HA Installed Version
    scan_interval: 86400
  - platform: command_line
    name: Python Version
    command: python3 --version
    scan_interval: 86400
################################################
## Group
################################################

group:
  host_view:
    name: Host
    view: yes
    entities:
      - sensor.bad_login
      - group.host_performance
      - group.host_storage
      - group.host_network
      - group.host_info
      - group.host_internet
      - group.host_batterij_zwave
  host_performance:
    # Systeeminformatie
    name: System Performance
    entities:
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.cpu_temperature
      - binary_sensor.cpu_high
      - binary_sensor.cpu_hot
  host_storage:
    name: System Storage
    entities:
      - sensor.disk_use_percent_
      - sensor.disk_free_
      - sensor.homeassistant_v2db
      - sensor.homeassistantlog
      - sensor.ozw_logtxt
      - sensor.configurationyaml
  host_network:
    name: Host Network
    entities:
      - sensor.network_out_eth0
      - sensor.network_in_eth0
      - sensor.packets_out_eth0
      - sensor.packets_in_eth0
      - sensor.myipopendnscom
      - sensor.ssl_certificate_expiry
  host_info:
    name: Home Assistant Info
    entities:
      - sensor.last_boot
      - sensor.ha_uptime
      - sensor.ha_installed_version
      - sensor.python_version
      - updater.updater
      - sensor.bad_login
  host_batterij_zwave:
    name: Batterij Percentages
    entities:
      - sensor.zwave_battery_front_door
      - sensor.zwave_battery_smoke_sensor_begane_grond
      - sensor.zwave_battery_smoke_sensor_slaapkamer_zolder
  host_internet:
    name: Internet
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
################################################
## Alert
################################################

alert:
  cpu_high:
    name: Gebruik CPU is hoog
    entity_id: binary_sensor.cpu_high
    state: 'on'
    repeat: 5 # minutes
    can_acknowledge: True
    skip_first: False
    notifiers:
      - telegram
  cpu_hot:
    name: Temperatuur CPU is hoog
    entity_id: binary_sensor.cpu_high
    state: 'on'
    repeat: 5 # minutes
    can_acknowledge: True
    skip_first: False
    notifiers:
      - telegram
  db_large:
    name: Database Large
    entity_id: binary_sensor.db_large
    state: 'on'
    repeat: # minutes
      - 15
      - 30
      - 60
      - 120
    can_acknowledge: true
    skip_first: false
    notifiers:
      - telegram

################################################
## Automation
################################################

automation:
  - alias: 'Update Available Notification'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: notify.telegram
        data:
          message: 'Update voor Home Assistant beschikbaar.'

################################################
## Notify
################################################

notify:
    - name: Telegram
      platform: telegram
      chat_id: !secret telegram_chat_id